spring.datasource.url=jdbc:postgresql://localhost:5433/task_manager
spring.datasource.username=task_user
spring.datasource.password=task_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=VGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9ySldUSFNIQTI1Ng==
jwt.expiration=86400000